
name: Spring Boot CI + Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : checkout code
        uses : actions/checkout@v4

      - name : set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name : Build and test with maven
        run : ./mvnw clean verify

      - name : Run OWASP Dependency Check
        uses : dependency-check/Dependency-Check_Action@main
        with :
          project: 'springboot-app'
          path: '.'
          format: ''

      - name : upload build artifact
        uses : actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

    deploy:
        needs : build
        runs-on : ubuntu-latest

        steps:
          - name : Checkout repo
            uses : actions/checkout@v4

          - name : Download build JAR
            uses : actions/download-artifact@v4
            with :
              name: app-jar

          - name : Set up Terraform
            uses : hashicorp/setup-terraform@v3
            with :
              terraform_version: 1.7.0

          - name : Initialize Terraform
            working-directory: terraform
            env:
              AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
              AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            run: terraform apply -auto-approve